# Generated by Django 4.2 on 2023-05-03 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderForUser',
            new_name='ReturnForUser',
        ),
    ]
